name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '0 8 * * 6'
jobs:
  test:
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: 1
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-20.04", "macos-latest"]
        python: ["2.7", "pypy-2.7", "3.5", "3.6", "3.7", "3.8", "3.9", "3.10", "pypy-3.9"]
        include:
          - os: "windows-latest"
            python: "3.8"
          - os: "windows-latest"
            python: "3.9"
          - os: "windows-latest"
            python: "3.10"
    runs-on: ${{ matrix.os }}
    name: "Test: Python ${{ matrix.python }} on ${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install tox tox-gh-actions
      - name: "Run tests"
        run: |
          python -m tox
          python -m tox -e coverage_report
      - uses: codecov/codecov-action@v3

  fmt:
    name: Format
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
      - uses: isort/isort-action@v1
